### PR TITLE
feat: create composer decorators

### PR DESCRIPTION
**Pull request by ByMsx**
Issue #30

### CODE REVIEW

**Review by solidprinciples — CHANGES_REQUESTED** [review]
LGTM, feel free to bump the versioning so we can publish on approval. Also - can we add to the changelog?

**Comment by ByMsx** [comment]
@solidprinciples It's ready!

**Comment by KnorpelSenf** [comment]
Please resolve the merge conflicts :)

**Review by solidprinciples — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
@solidprinciples feel free to merge and release

**Comment by ByMsx** [comment]
@solidprinciples , any updates?.. 👉 👈

**Comment by ByMsx** [comment]
@solidprinciples , any updates?..

**Comment by ByMsx** [comment]
@solidprinciples , merge conflicts are resolved

**Review by solidprinciples — APPROVED** [review]

**Pull request merged**
